### ISSUE TITLE
Cannot make can0 work

### ISSUE THREAD

**Issue by amarce** [pierremolinaro/acanfd-feather-m4-can#1]
Hi,

I've installed a transceiver on the can0 of the feather m4 can express, and I cannot make it work. No data is being received there. I've tried with a CJMCU-1051 TJA1051 and a SN65HVD230 transceiver (The first one is new, so don't know if it was working, the second one was tested and working perfectly). I've wired the cantx with the cantx and the canrx with the canrx so it should work perfectly.

Everything works well on can1 (Onboard can). Have you encountered this problem? Can this be due to the transceivers used?

Thanks a lot!

**Comment by pierremolinaro** [comment]
Hi,

How do you power the transceivers ?

Be carefully, there are several different components called TJA1051, you should use an TJA1051T/3 that has a Vio pin. So Vio (pin #5) -> 3.3V, Vcc (pin #3) -> 5V, S (Silent mode, pin #8) -> GND.

 For the SN65HVD230, Vcc (pin #3) -> 3.3V, RS (pin #8) -> GND.

Best Regards,

Pierre

**Comment by amarce** [comment]
Hi,

Thanks for you reply; the TJA1051 board works from 3 to 5V and the SN65HVD230 board works with 3.3v right (I've tested it on an arduino DUE). I think that my problem is that I was making the led flicker with:

```
void LedLoop() {
  if (ledActive==0){  
    if ((ledMillis==0) || ( millis() >= ledMillis + ledFlickTime )) {  
      //Turn on red led  
      digitalWrite(13, HIGH);  
      ledMillis = millis();  
      ledActive=1;  
    }  
  } else {  
     if ((ledMillis==0) || ( millis() >= ledMillis + ledFlickTime )) {  
      //Turn off red led  
      digitalWrite(13, LOW);  
      ledMillis = millis();  
      ledActive=0;  
    }  
  }  
}
```

So I was sending power to the rx pin of the transceiver, and for sure this was making it not working. I'll try tomorrow with the flickering disabled, but I'm pretty confident that the problem is here (I've seen it reading the PDF on the extras folder when you say that the same PIN is used on the onboard led and I did not notice).

I will check tomorrow morning and let you know if this was the problem (And close the issue if it was the case).

Again, thanks a lot!

**Comment by amarce** [comment]
Hi,

I've been testing and it seems that something odd is happening on my board; if I press the processor down the red led illuminates, so it makes me thing that something is being shorted on the circuit.

I've ordered a new feather M4 to test it outside of any circuit, but it really looks like a hardware error. I'm clossing the issue because it does not seem software related.

Thanks a lot!
